//@version=6
strategy("Volty Expan Close Strategy", overlay=true, use_bar_magnifier=false, initial_capital=1000000, currency=currency.USD, process_orders_on_close=false, pyramiding=1, commission_type=strategy.commission.percent, commission_value=0, slippage=0, default_qty_type=strategy.fixed, default_qty_value=1)
length = input(5, "Length")
numATRs = input(0.75, "ATR Mult")
atrs = ta.sma(ta.tr, length)*numATRs
if (not na(close[length]))
	strategy.entry("VltClsLE", strategy.long, stop=close+atrs, comment = "VltClsLE")
	strategy.entry("VltClsSE", strategy.short, stop=close-atrs, comment = "VltClsSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)