//@version=6
strategy("InSide Bar Strategy", overlay=true, use_bar_magnifier=false, initial_capital=1000000, currency=currency.USD, process_orders_on_close=false, pyramiding=1, commission_type=strategy.commission.percent, commission_value=0, slippage=0, default_qty_type=strategy.fixed, default_qty_value=1)
if (high < high[1] and low > low[1])
	if (close > open)
		strategy.entry("InsBarLE", strategy.long, comment="InsBarLE")
	if (close < open)
		strategy.entry("InsBarSE", strategy.short, comment="InsBarSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)