//@version=6
strategy("Stochastic Slow Strategy", overlay=true, use_bar_magnifier=false, initial_capital=1000000, currency=currency.USD, process_orders_on_close=false, pyramiding=1, commission_type=strategy.commission.percent, commission_value=0, slippage=0, default_qty_type=strategy.fixed, default_qty_value=1)
length = input.int(14, "Length", minval=1)
OverBought = input(80, "Overbought")
OverSold = input(20, "Oversold")
smoothK = 3
smoothD = 3
k = ta.sma(ta.stoch(close, high, low, length), smoothK)
d = ta.sma(k, smoothD)
co = ta.crossover(k,d)
cu = ta.crossunder(k,d)
if (not na(k) and not na(d))
	if (co and k < OverSold)
		strategy.entry("StochLE", strategy.long, comment="StochLE")
	if (cu and k > OverBought)
		strategy.entry("StochSE", strategy.short, comment="StochSE")
//plot(strategy.equity, title="equity", color=color.red, linewidth=2, style=plot.style_areabr)